---
title: "Assignment4"
author: "Neve/Viva/Yaohan"
date: "`r Sys.Date()`"
output: 
  html_document:
    keep_md: yes
    toc: yes
    theme: flatly
    toc_float: yes
    code_folding: hide
    number_sections: no
  pdf_document:
    toc: yes
---

```{=html}
<style>
.kable thead tr th, .table thead tr th {
  text-align: left !important;}
table.kable, table.table {
  width: 100% !important;}
  body {
  line-height: 1.6;
  font-size: 16px
}
</style>
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  cache = TRUE,
  dpi = 150)
options(scipen = 999)

if(!require(pacman)){install.packages("pacman"); library(pacman)}
p_load(tidyverse, sf, units, nngeo, tmap, tinytex, kableExtra, janitor, classInt,
       patchwork, here, tidycensus, lwgeom, lsr, haven, descr, RColorBrewer, stargazer,
       car, FNN, GGally, MASS, ISLR2, spdep, caret, ckanr, grid, gridExtra, ggcorrplot,
       jtools, broom, tufte, rmarkdown, corrr, RSocrata, viridis, spatstat, raster, knitr,
       classInt, jsonlite)

library(conflicted)
conflicts_prefer(dplyr::select)
conflicts_prefer(dplyr::filter)
```

```{r}
dat <- read_csv(here::here('data/raw/NIJ_s_Recidivism_Challenge_Full_Dataset_20240418.csv'))


```

# Discussion

# Plot of Variables

# Model Develop

# Result Interpretation
1. Model Result 

2. Most Risky Person

# ROC Curve

# Confusion Matrix

# Sensitivity and Specificity

# Prediction

## Error

## Summary by Race

## Equity Discussion

# Cost-Benifit Analysis

# Conclusion




